import { Room, Building } from "./types";

export const ROOMS: {
  [key: string]: Room;
} = {
  ALEX100: {
    name: "Alexander Hall - Room 100",
    type: "Room",
    short: "ALEX100",
    href: "/rooms/ALEX100",
    image: "/images/rooms/ALEX100.jpg",
    info: {
      type: "Lecture Theatre",
      seating: "Fixed Chairs with Tablets",
      capacity: 182,
    },
  },
  ALEX200: {
    name: "Alexander Hall - Room 200",
    type: "Room",
    short: "ALEX200",
    href: "/rooms/ALEX200",
    image: "/images/rooms/ALEX200.jpg",
    info: {
      type: "Lecture Theatre",
      seating: "Fixed Chairs with Tablets",
      capacity: 322,
    },
  },
};

export const BUILDINGS: {
  [key: string]: Building;
} = {
  ALEX: {
    name: "Alexander Hall",
    type: "Building",
    short: "ALEX",
    image: "/images/buildings/ALEX.jpg",
    href: "/buildings/ALEX",
    rooms: ["ALEX100", "ALEX200"],
  },
  CRSC: {
    name: "Crop Science",
    type: "Building",
    short: "CRSC",
    image: "",
    href: "/buildings/CRSC",
    rooms: [] as string[],
  },
  HUTT: {
    name: "H.L. Hutt",
    type: "Building",
    short: "HUTT",
    image: "",
    href: "/buildings/HUTT",
    rooms: [] as string[],
  },
  ANNU: {
    name: "Animal Sci. & Nutri.",
    type: "Building",
    short: "ANNU",
    image: "",
    href: "/buildings/ANNU",
    rooms: [] as string[],
  },
  FS: {
    name: "Food Science",
    type: "Building",
    short: "FS",
    image: "",
    href: "/buildings/FS",
    rooms: [] as string[],
  },
  LA: {
    name: "Landscape Architecture",
    type: "Building",
    short: "LA",
    image: "",
    href: "/buildings/LA",
    rooms: [] as string[],
  },
  MAC: {
    name: "Macdonald Hall",
    type: "Building",
    short: "MAC",
    image: "",
    href: "/buildings/MAC",
    rooms: [] as string[],
  },
  MACK: {
    name: "Mackinnon",
    type: "Building",
    short: "MACK",
    image: "",
    href: "/buildings/MACK",
    rooms: [] as string[],
  },
  MACN: {
    name: "MacNaughton",
    type: "Building",
    short: "MACN",
    image: "",
    href: "/buildings/MACN",
    rooms: [] as string[],
  },
  MACS: {
    name: "Macdonald Stewart",
    type: "Building",
    short: "MACS",
    image: "",
    href: "/buildings/MACS",
    rooms: [] as string[],
  },
  MCLN: {
    name: "Maclachlan",
    type: "Building",
    short: "MCLN",
    image: "",
    href: "/buildings/MCLN",
    rooms: [] as string[],
  },
  MINS: {
    name: "MacDonald Institute",
    type: "Building",
    short: "MINS",
    image: "",
    href: "/buildings/MINS",
    rooms: [] as string[],
  },
  ROZH: {
    name: "Rozanski Hall",
    type: "Building",
    short: "ROZH",
    image: "",
    href: "/buildings/ROZH",
    rooms: [] as string[],
  },
  SCIE: {
    name: "Science Complex",
    type: "Building",
    short: "SCIE",
    image: "",
    href: "/buildings/SCIE",
    rooms: [] as string[],
  },
  THRN: {
    name: "A. A. Thornbrough",
    type: "Building",
    short: "THRN",
    image: "",
    href: "/buildings/THRN",
    rooms: [] as string[],
  },
  WMEM: {
    name: "War Memorial Hall",
    type: "Building",
    short: "WMEM",
    image: "",
    href: "/buildings/WMEM",
    rooms: [] as string[],
  },
};
