import { Room } from "./types";

export const BUILDINGS = {
  ALEX: {
    name: "Alexander Hall",
    type: "Building",
    short: "ALEX",
    href: "/find/building/ALEX",
    rooms: [] as Room[],
  },
  CRSC: {
    name: "Crop Science",
    type: "Building",
    short: "CRSC",
    href: "/find/building/CRSC",
    rooms: [] as Room[],
  },
  HUTT: {
    name: "H.L. Hutt",
    type: "Building",
    short: "HUTT",
    href: "/find/building/HUTT",
    rooms: [] as Room[],
  },
  ANNU: {
    name: "Animal Sci. & Nutri.",
    type: "Building",
    short: "ANNU",
    href: "/find/building/ANNU",
    rooms: [] as Room[],
  },
  FS: {
    name: "Food Science",
    type: "Building",
    short: "FS",
    href: "/find/building/FS",
    rooms: [] as Room[],
  },
  LA: {
    name: "Landscape Architecture",
    type: "Building",
    short: "LA",
    href: "/find/building/LA",
    rooms: [] as Room[],
  },
  MAC: {
    name: "Macdonald Hall",
    type: "Building",
    short: "MAC",
    href: "/find/building/MAC",
    rooms: [] as Room[],
  },
  MACK: {
    name: "Mackinnon",
    type: "Building",
    short: "MACK",
    href: "/find/building/MACK",
    rooms: [] as Room[],
  },
  MACN: {
    name: "MacNaughton",
    type: "Building",
    short: "MACN",
    href: "/find/building/MACN",
    rooms: [] as Room[],
  },
  MACS: {
    name: "Macdonald Stewart",
    type: "Building",
    short: "MACS",
    href: "/find/building/MACS",
    rooms: [] as Room[],
  },
  MCLN: {
    name: "Maclachlan",
    type: "Building",
    short: "MCLN",
    href: "/find/building/MCLN",
    rooms: [] as Room[],
  },
  MINS: {
    name: "MacDonald Institute",
    type: "Building",
    short: "MINS",
    href: "/find/building/MINS",
    rooms: [] as Room[],
  },
  ROZH: {
    name: "Rozanski Hall",
    type: "Building",
    short: "ROZH",
    href: "/find/building/ROZH",
    rooms: [] as Room[],
  },
  SCIE: {
    name: "Science Complex",
    type: "Building",
    short: "SCIE",
    href: "/find/building/SCIE",
    rooms: [] as Room[],
  },
  THRN: {
    name: "A. A. Thornbrough",
    type: "Building",
    short: "THRN",
    href: "/find/building/THRN",
    rooms: [] as Room[],
  },
  WMEM: {
    name: "War Memorial Hall",
    type: "Building",
    short: "WMEM",
    href: "/find/building/WMEM",
    rooms: [] as Room[],
  },
};
