import { Building } from "../types";

export const BUILDINGS: {
  [key: string]: Building;
} = {
  ALEX: {
    name: "Alexander Hall",
    type: "Building",
    short: "ALEX",
    address: "570 Gordon St, Guelph, ON N1G 2W1",
    image: "/images/buildings/ALEX.jpg",
    href: "/buildings/ALEX",
    rooms: ["ALEX100", "ALEX200"],
  },
  HUTT: {
    name: "H.L. Hutt",
    type: "Building",
    short: "HUTT",
    address: "43 Reynolds Walk, Guelph, ON N1G 2W1",
    image: "/images/buildings/HUTT.jpg",
    href: "/buildings/HUTT",
    rooms: [
      "HUTT233",
      "HUTT234",
      "HUTT235",
      "HUTT236",
      "HUTT240A",
      "HUTT240B",
      "HUTT240C",
    ],
  },
  ANNU: {
    name: "Animal Sci. & Nutri.",
    type: "Building",
    short: "ANNU",
    address: "541 County Road 46, Guelph, ON N1G 2W1",
    image: "/images/buildings/ANNU.jpg",
    href: "/buildings/ANNU",
    rooms: [
      "ANNU102",
      "ANNU103",
      "ANNU104",
      "ANNU105",
      "ANNU107",
      "ANNU110",
      "ANNU115",
      "ANNU116",
      "ANNU129",
      "ANNU130",
      "ANNU131",
      "ANNU133",
      "ANNU141",
      "ANNU156",
      "ANNU204",
      "ANNU205",
      "ANNU208",
      "ANNU212",
      "ANNU214",
      "ANNU215",
      "ANNU216",
      "ANNU217",
      "ANNU218",
      "ANNU220",
      "ANNU302",
      "ANNU305",
      "ANNU306",
      "ANNU327",
      "ANNU337",
      "ANNU355",
    ],
  },
  FS: {
    name: "Food Science",
    type: "Building",
    short: "FS",
    address: "Alumni Walk / Gordon Street, Guelph, ON N1G 2W1",
    image: "/images/buildings/FS.jpg",
    href: "/buildings/FS",
    rooms: ["FS102", "FS128", "FS129", "FS241", "FS246"],
  },
  LA: {
    name: "Landscape Architecture",
    type: "Building",
    short: "LA",
    address: "Reynolds Walk/Powerhouse Lane, Guelph, ON N1G 2W1",
    image: "/images/buildings/LA.jpg",
    href: "/buildings/LA",
    rooms: [] as string[],
  },
  MAC: {
    name: "Macdonald Hall",
    type: "Building",
    short: "MAC",
    address: "74 Macdonald St Guelph, ON N1G 1M8",
    image: "/images/buildings/MAC.jpg",
    href: "/buildings/MAC",
    rooms: ["MAC149"],
  },
  MACK: {
    name: "Mackinnon",
    type: "Building",
    short: "MACK",
    address: "87 Trent Ln, Guelph, ON N1G 1Y4",
    image: "/images/buildings/MACK",
    href: "/buildings/MACK",
    rooms: [] as string[],
  },
  MACN: {
    name: "MacNaughton",
    type: "Building",
    short: "MACN",
    address: "Reynolds Walk/Winegard Walk, Guelph, ON N1G 1Y4",
    image: "/images/buildings/MACN.jpg",
    href: "/buildings/MACN",
    rooms: [] as string[],
  },
  MACS: {
    name: "Macdonald Stewart",
    type: "Building",
    short: "MACS",
    address: "62 Macdonald Street, Guelph, ON N1G 1Y1",
    image: "/images/buildings/MACS.jpg",
    href: "/buildings/MACS",
    rooms: ["MACS117", "MACS121", "MACS129"],
  },
  MCLN: {
    name: "Maclachlan",
    type: "Building",
    short: "MCLN",
    address: "476 Gordon St, Guelph, ON N1G 1Y4",
    image: "/images/buildings/MCLN.jpg",
    href: "/buildings/MCLN",
    rooms: ["MCLN101", "MCLN102", "MCLN103", "MCLN107"],
  },
  MINS: {
    name: "MacDonald Institute",
    type: "Building",
    short: "MINS",
    address: "50 Macdonald St, Guelph, ON N1G 1M8",
    image: "/images/buildings/MINS.jpg",
    href: "/buildings/MINS",
    rooms: [] as string[],
  },
  ROZH: {
    name: "Rozanski Hall",
    type: "Building",
    short: "ROZH",
    address: "98 Trent Ln, Guelph, ON N1G 1Y1",
    image: "/images/buildings/ROZH.jpg",
    href: "/buildings/ROZH",
    rooms: [] as string[],
  },
  SCIE: {
    name: "Science Complex",
    type: "Building",
    short: "SCIE",
    address: "474-570 Gordon St, Guelph, ON N1G 1Y2",
    image: "/images/buildings/SCIE.jpg",
    href: "/buildings/SCIE",
    rooms: [] as string[],
  },
  THRN: {
    name: "A. A. Thornbrough",
    type: "Building",
    short: "THRN",
    address: "80 South Ring Rd E, Guelph, ON N1G 1Y1",
    image: "/images/buildings/THRN.jpg",
    href: "/buildings/THRN",
    rooms: [] as string[],
  },
  WMEM: {
    name: "War Memorial Hall",
    type: "Building",
    short: "WMEM",
    address: "Gordon St/College Ave E, Guelph, ON N1G 1Y4",
    image: "/images/buildings/WMEM.jpg",
    href: "/buildings/WMEM",
    rooms: ["WMEM"],
  },
  CRSC: {
    name: "Crop Science",
    type: "Building",
    short: "CRSC",
    address: "117 Reynolds Walk, Guelph, ON N1G 1Y4",
    image: "/images/buildings/CRSC.jpg",
    href: "/buildings/CRSC",
    rooms: [
      "CRSC101",
      "CRSC104",
      "CRSC105",
      "CRSC106",
      "CRSC107",
      "CRSC109",
      "CRSC110",
      "CRSC112",
      "CRSC113",
      "CRSC114",
      "CRSC116",
      "CRSC117",
      "CRSC118",
      "CRSC118A",
      "CRSC119",
      "CRSC120",
      "CRSC121",
      "CRSC122",
      "CRSC123",
      "CRSC124",
      "CRSC127",
      "CRSC133",
      "CRSC134",
      "CRSC136",
      "CRSC138",
      "CRSC139",
      "CRSC140",
      "CRSC141",
      "CRSC143",
      "CRSC144",
      "CRSC151",
      "CRSC205",
      "CRSC210",
      "CRSC216",
      "CRSC219",
      "CRSC222",
      "CRSC225",
      "CRSC302",
      "CRSC302A",
      "CRSC307",
      "CRSC308",
      "CRSC310",
      "CRSC318",
      "CRSC322",
      "CRSC403",
      "CRSC411",
      "CRSC415",
      "CRSC418",
      "CRSC419",
      "CRSC426",
    ],
  },
};
