import { Building } from "../types";

export const BUILDINGS: {
  [key: string]: Building;
} = {
  ALEX: {
    name: "Alexander Hall",
    type: "Building",
    short: "ALEX",
    image: "/images/buildings/ALEX.jpg",
    href: "/buildings/ALEX",
    rooms: ["ALEX100", "ALEX200"],
  },
  CRSC: {
    name: "Crop Science",
    type: "Building",
    short: "CRSC",
    image: "/images/buildings/CRSC.jpg",
    href: "/buildings/CRSC",
    rooms: [] as string[],
  },
  HUTT: {
    name: "H.L. Hutt",
    type: "Building",
    short: "HUTT",
    image: "/images/buildings/HUTT.jpg",
    href: "/buildings/HUTT",
    rooms: [] as string[],
  },
  ANNU: {
    name: "Animal Sci. & Nutri.",
    type: "Building",
    short: "ANNU",
    image: "/images/buildings/ANNU.jpg",
    href: "/buildings/ANNU",
    rooms: [] as string[],
  },
  FS: {
    name: "Food Science",
    type: "Building",
    short: "FS",
    image: "/images/buildings/FS.jpg",
    href: "/buildings/FS",
    rooms: [] as string[],
  },
  LA: {
    name: "Landscape Architecture",
    type: "Building",
    short: "LA",
    image: "/images/buildings/LA.jpg",
    href: "/buildings/LA",
    rooms: [] as string[],
  },
  MAC: {
    name: "Macdonald Hall",
    type: "Building",
    short: "MAC",
    image: "/images/buildings/MAC.jpg",
    href: "/buildings/MAC",
    rooms: [] as string[],
  },
  MACK: {
    name: "Mackinnon",
    type: "Building",
    short: "MACK",
    image: "/images/buildings/MACK",
    href: "/buildings/MACK",
    rooms: [] as string[],
  },
  MACN: {
    name: "MacNaughton",
    type: "Building",
    short: "MACN",
    image: "/images/buildings/MACN.jpg",
    href: "/buildings/MACN",
    rooms: [] as string[],
  },
  MACS: {
    name: "Macdonald Stewart",
    type: "Building",
    short: "MACS",
    image: "/images/buildings/MACS.jpg",
    href: "/buildings/MACS",
    rooms: [] as string[],
  },
  MCLN: {
    name: "Maclachlan",
    type: "Building",
    short: "MCLN",
    image: "/images/buildings/MCLN.jpg",
    href: "/buildings/MCLN",
    rooms: [] as string[],
  },
  MINS: {
    name: "MacDonald Institute",
    type: "Building",
    short: "MINS",
    image: "/images/buildings/MINS.jpg",
    href: "/buildings/MINS",
    rooms: [] as string[],
  },
  ROZH: {
    name: "Rozanski Hall",
    type: "Building",
    short: "ROZH",
    image: "/images/buildings/ROZH.jpg",
    href: "/buildings/ROZH",
    rooms: [] as string[],
  },
  SCIE: {
    name: "Science Complex",
    type: "Building",
    short: "SCIE",
    image: "/images/buildings/SCIE.jpg",
    href: "/buildings/SCIE",
    rooms: [] as string[],
  },
  THRN: {
    name: "A. A. Thornbrough",
    type: "Building",
    short: "THRN",
    image: "/images/buildings/THRN.jpg",
    href: "/buildings/THRN",
    rooms: [] as string[],
  },
  WMEM: {
    name: "War Memorial Hall",
    type: "Building",
    short: "WMEM",
    image: "/images/buildings/WMEM.jpg",
    href: "/buildings/WMEM",
    rooms: ["WMEM"],
  },
};
